### ISSUE TITLE
使用adb模式组队刷魂十，魂十结束会报错

### ISSUE THREAD

**Issue by Rambox1** [anywheretogo/YYS#3]
Traceback (most recent call last):
  File "D:/Rambo/study/python/YYS/yys_adb.py", line 20, in wrap
    ans = f(*agrs, **kwagrs)
  File "D:/Rambo/study/python/YYS/yys_adb.py", line 43, in select_mode
    comand()
  File "D:/Rambo/study/python/YYS/yys_adb.py", line 76, in yuhun
    target = action.cut(screen, x1, x2)
  File "D:\Rambo\study\python\YYS\action_adb.py", line 91, in cut
    screen = screen[b:d,a:c]
TypeError: 'NoneType' object is not subscriptable
2189 KB/s (789512 bytes in 0.352s)
libpng error: Read Error

**Comment by anywhere2go** [comment]
会重复出现么。。看提示应该是截图读取失败，可能是截图文件从手机模拟器PULL到电脑时读写出错

**Comment by Rambox1** [comment]
是的 只能刷一次。不知道是不是我配置的问题 我看着screen.jpg也覆盖了。
