### ISSUE TITLE
求楼主解答，cv2调取图片时提示返回类型是none

### ISSUE THREAD

**Issue by asd857671844** [anywheretogo/YYS#7]
Traceback (most recent call last):
  File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 20, in wrap
    ans = f(*agrs, **kwagrs)
  File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 43, in select_mode
    comand()
  File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 87, in yuhun
    size = want[0].shape
AttributeError: 'NoneType' object has no attribute 'shape'
screen shot ok Sun Jun  2 08:18:41 2019

Process finished with exit code 0

**Comment by yulele166** [comment]
> Traceback (most recent call last):
> File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 20, in wrap
> ans = f(*agrs, **kwagrs)
> File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 43, in select_mode
> comand()
> File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 87, in yuhun
> size = want[0].shape
> AttributeError: 'NoneType' object has no attribute 'shape'
> screen shot ok Sun Jun 2 08:18:41 2019
> 
> Process finished with exit code 0

大佬 解决了吗

**Comment by anywhere2go** [comment]
这个opencv读取图标文件时出错，你们看下yuhun.jpg这个图标是否读取成功了

**Comment by asd857671844** [comment]
你好，那个你存放在jpg文件里没有yuhun.jpg这个文件

**Comment by anywheretogo** [comment]
你看下是不是路径有中文，导致读取图片失败

**Comment by anywhere2go** [comment]
> Traceback (most recent call last):
> File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 20, in wrap
> ans = f(*agrs, **kwagrs)
> File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 43, in select_mode
> comand()
> File "C:/Users/jane wang/Desktop/阴阳师脚本/YYS-master/yys.py", line 87, in yuhun
> size = want[0].shape
> AttributeError: 'NoneType' object has no attribute 'shape'
> screen shot ok Sun Jun 2 08:18:41 2019
> 
> Process finished with exit code 0

注意路径不能有中文，会导致opencv读取文件失败

**Comment by anywhere2go** [comment]
> 你好，那个你存放在jpg文件里没有yuhun.jpg这个文件

你看下是不是因为文件目录有中文

**Comment by mengxiu** [comment]
我也遇到了，你把main里图片的路径改一改
